export const GET_SCHEDULE_DATA_REQUEST = "GET_SCHEDULE_DATA_REQUEST";
export const GET_SCHEDULE_DATA_SUCCESS = "GET_SCHEDULE_DATA_SUCCESS";
export const GET_SCHEDULE_DATA_FAILED = "GET_SCHEDULE_DATA_FAILED";
